CREATE TABLE COMERCIAL
(id NUMBER (10),
nombre VARCHAR2 (100),
apellido1 VARCHAR2 (100),
apellido2 VARCHAR2 (100),
ciudad VARCHAR2 (100),
comision FLOAT,

CONSTRAINT PK_COMERCIAL PRIMARY KEY (id)


);
CREATE TABLE CLIENTE
(id NUMBER (10),
nombre VARCHAR2 (100),
apellido1 VARCHAR2 (100),
apellido2 VARCHAR2 (100),
ciudad VARCHAR2 (100),
categoria NUMBER (10),

CONSTRAINT PK_CLIENTE PRIMARY KEY (id)

);



CREATE TABLE PEDIDO

(id NUMBER (10),
cantidad NUMBER,
fecha DATE,
id_cliente NUMBER (10),
id_comercial NUMBER (10),

CONSTRAINT PK_PEDIDO PRIMARY KEY (id),
CONSTRAINT FK1_PEDIDO FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id),
CONSTRAINT FK2_PEDIDO FOREIGN KEY (id_comercial) REFERENCES COMERCIAL (id)
);







