
CREATE TABLE TEMA
(cod_tema NUMBER (10),
denominacion VARCHAR2 (20),
cod_tema_padre NUMBER (15),
	
CONSTRAINT PK_TEMA PRIMARY KEY (cod_tema),
CONSTRAINT FK_TEMA FOREIGN KEY (cod_tema_padre) REFERENCES TEMA (cod_tema) ON DELETE CASCADE,
CONSTRAINT res_tema CHECK (cod_tema_padre>=cod_tema)
);

CREATE TABLE LIBRO
(cod_libro VARCHAR2(10),
titulo VARCHAR2 (20),
f_creacion DATE,
cod_tema NUMBER (10),
autor_principal VARCHAR2 (20),
	
CONSTRAINT PK_LIBRO PRIMARY KEY (cod_libro),
CONSTRAINT FK_LIBRO FOREIGN KEY (cod_tema) REFERENCES TEMA (cod_tema)

);


CREATE TABLE AUTOR
(cod_autor VARCHAR2(10),
Nombre VARCHAR2(15),
f_nacimiento DATE,
libro_principal VARCHAR2(10),
	
CONSTRAINT PK_AUTOR PRIMARY KEY (cod_autor),
CONSTRAINT FK_AUTOR FOREIGN KEY (libro_principal) REFERENCES LIBRO(cod_libro)

);

ALTER TABLE LIBRO ADD CONSTRAINT FK_INSERT FOREIGN KEY (autor_principal) REFERENCES AUTOR (cod_autor);

CREATE TABLE LIBRO_AUTOR 
(cod_libro VARCHAR2(10),
cod_autor VARCHAR2(10),
orden NUMBER (5),

CONSTRAINT PK_LIBRO_AUTOR PRIMARY KEY (cod_libro, cod_autor),
CONSTRAINT FK_LIBRO_AUTOR FOREIGN KEY (cod_libro) REFERENCES LIBRO(cod_libro) ON DELETE CASCADE,
CONSTRAINT FK_AUTOR_LIBRO FOREIGN KEY (cod_autor) REFERENCES AUTOR(cod_autor) ON DELETE CASCADE
);

ALTER TABLE LIBRO_AUTOR ADD CONSTRAINT res_orden CHECK (orden>=1 AND orden<=5)


CREATE TABLE EDITORIAL
(cod_editorial VARCHAR2 (10),
denominacion VARCHAR2 (20),

CONSTRAINT PK_EDITORIAL PRIMARY KEY (cod_editorial)

);


CREATE TABLE PUBLICACIONES
(cod_editorial VARCHAR2 (10),
cod_libro VARCHAR2 (10),
precio NUMBER (20),
f_publicacion DATE DEFAULT sysdate,

CONSTRAINT PK_PUBLICACIONES PRIMARY KEY (cod_editorial, cod_libro),
CONSTRAINT FK_PUBLICACIONES_2 FOREIGN KEY (cod_libro) REFERENCES LIBRO(cod_libro),
CONSTRAINT FK_PUBLICACIONES_3 FOREIGN KEY (cod_editorial) REFERENCES EDITORIAL (cod_editorial)



);

 
ALTER TABLE PUBLICACIONES ADD CONSTRAINT CHK_PRECIO CHECK (precio >0)



