--ALTER SESSION SET "_oracle_script"=TRUE;
--CREATE USER VILLARREAL_HINOJO_VICENTE_2 IDENTIFIED BY VILLARREAL_HINOJO_VICENTE_2;
--GRANT CONNECT, RESOURCE, DBA TO VILLARREAL_HINOJO_VICENTE_2;

CREATE TABLE CLIENTES
(dni VARCHAR2 (20),
nombre VARCHAR2 (20),
apellidos VARCHAR2 (20),
ciudad VARCHAR2(20),

CONSTRAINT PK_CLIENTES PRIMARY KEY (dni)
);

CREATE TABLE CONCESIONARIOS_1
(cifc VARCHAR2 (10),

CONSTRAINT PK_CONCESIONARIOS1 PRIMARY KEY (cifc)
);

CREATE TABLE CONCESIONARIOS
(cifc VARCHAR2 (10),
nombre VARCHAR2 (20),
ciudad VARCHAR2 (20),
cifcmatriz VARCHAR2 (10),

CONSTRAINT PK_CONCESIONARIOS PRIMARY KEY (cifc),
CONSTRAINT FK_CONCESIONARIOS FOREIGN KEY (cifcmatriz) REFERENCES CONCESIONARIOS_1 (cifc)
);




CREATE TABLE VENTAS
(codcoche NUMBER(5),
cifc VARCHAR2 (10),
dni VARCHAR2(20),
fechaVenta DATE,
pvp NUMBER (20),

CONSTRAINT PK_VENTAS PRIMARY KEY(codcoche),
CONSTRAINT FK_VENTAS FOREIGN KEY (dni) REFERENCES CLIENTES (dni),
CONSTRAINT FK1_VENTAS FOREIGN KEY (cifc) REFERENCES CONCESIONARIOS (cifc)
);

CREATE TABLE MARCAS
(codmarca NUMBER(5),
nombre VARCHAR2 (10),
pais VARCHAR2 (10),

CONSTRAINT PK_MARCAS PRIMARY KEY (codmarca)

);


CREATE TABLE COCHES 
(codcoche NUMBER (5),
codmarca NUMBER (5),
modelo VARCHAR2 (10),
matricula VARCHAR2(10),
color VARCHAR2 (10),

CONSTRAINT PK_COCHES PRIMARY KEY (codcoche),
CONSTRAINT FK_COCHES FOREIGN KEY (codmarca) REFERENCES MARCAS (codmarca)
);


CREATE TABLE DISTRIBUCION 
(cifc VARCHAR2 (10),
codcoche NUMBER (5),
fecha DATE,

CONSTRAINT PK_DISTRIBUCION PRIMARY KEY (cifc, codcoche),
CONSTRAINT FK_DISTRIBUCION FOREIGN KEY (cifc) REFERENCES CONCESIONARIOS (cifc),
CONSTRAINT FK1_DISTRIBUCION FOREIGN KEY (codcoche) REFERENCES COCHES (codcoche)

);

ALTER TABLE VENTAS ADD CONSTRAINT CH_VENTAS CHECK (fechaVenta = (DEFAULT =SYSDATE));
ALTER TABLE COCHES ADD CONSTRAINT CH1_COCHES CHECK (color IN ('rojo','amarillo', 'verde','ROJO','AMARILLO','VERDE'));
ALTER TABLE CLIENTES ADD CONSTRAINT CH2_CLIENTES CHECK (ciudad=UPPER(CIUDAD));
ALTER TABLE CONCESIONARIOS ADD CONSTRAINT CH2_CONCESIONARIOS CHECK (ciudad=UPPER(CIUDAD));
ALTER TABLE DISTRIBUCION ADD  area VARCHAR2 (10);




