CREATE TABLE FABRICANTES
(cod_fabricante NUMBER (3),
nombre VARCHAR2 (15),
pais VARCHAR2 (15),

CONSTRAINT PK_FABRICANTES PRIMARY KEY (cod_fabricante),
CONSTRAINT CH_FABRICANTES CHECK (nombre=UPPER(NOMBRE)),
CONSTRAINT CH_FABRICANTES2 CHECK (pais=UPPER(PAIS))
);

CREATE TABLE TIENDAS
(nif VARCHAR2 (10),
nombre VARCHAR2 (20),
direccion VARCHAR2 (20),
poblacion VARCHAR2 (20),
provincia VARCHAR2 (20),
codpostal NUMBER (5),

CONSTRAINT PK_TIENDAS PRIMARY KEY (nif),
CONSTRAINT CH_TIENDAS CHECK (provincia=UPPER (PROVINCIA))
);

CREATE TABLE ARTICULOS
(articulo VARCHAR2 (20) NOT NULL,
cod_fabricante NUMBER (3) NOT NULL,
peso NUMBER (30) NOT NULL,
categoria VARCHAR2 (10) NOT NULL,
precio_venta NUMBER(4,2),
precio_costo NUMBER (4,2),
existencias NUMBER(5),

CONSTRAINT PK_ARTICULOS PRIMARY KEY (articulo, cod_fabricante, peso, categoria),
CONSTRAINT FK_ARTICULOS FOREIGN KEY (cod_fabricante) REFERENCES FABRICANTES (cod_fabricante),
CONSTRAINT CH_ARTICULOS CHECK (precio_venta>0),
CONSTRAINT CH_ARTICULOS2 CHECK (precio_costo>0),
CONSTRAINT CH_ARTICULOS3 CHECK (peso>0),
CONSTRAINT CH_ARTICULOS4 CHECK (categoria IN ('PRIMERA','SEGUNDA', 'TERCERA'))
);

CREATE TABLE PEDIDOS
(nif VARCHAR2(10) NOT NULL,
articulo VARCHAR2 (20) NOT NULL,
cod_fabricante NUMBER(3) NOT NULL,
peso NUMBER(3) NOT NULL,
categoria VARCHAR2 (10) NOT NULL,
fecha_pedidos DATE NOT NULL,
unidades_pedidas NUMBER(4),

CONSTRAINT PK_PEDIDOS PRIMARY KEY (nif, articulo, cod_fabricante, peso, categoria, fecha_pedidos),
CONSTRAINT FK_PEDIDOS FOREIGN KEY (cod_fabricante) REFERENCES FABRICANTES (cod_fabricante) ON DELETE CASCADE,
CONSTRAINT CH_PEDIDOS CHECK (unidades_pedidas >0),
CONSTRAINT FK_PEDIDOS3 FOREIGN KEY (articulo, cod_fabricante, peso, categoria) REFERENCES ARTICULOS (articulo, cod_fabricante, peso, categoria) ON DELETE CASCADE,
CONSTRAINT FK_PEDIDOS5 FOREIGN KEY (nif) REFERENCES TIENDAS (nif)
);

CREATE TABLE VENTAS
(nif  VARCHAR2 (10) NOT NULL,
articulo VARCHAR2 (20) NOT NULL,
cod_fabricante NUMBER (3) NOT NULL,
peso NUMBER (3) NOT NULL,
categoria VARCHAR2 (10) NOT NULL,
fecha_venta DATE DEFAULT SYSDATE NOT NULL,
unidades_vendidas NUMBER(4),

CONSTRAINT PK_VENTAS PRIMARY KEY (nif, articulo, cod_fabricante, peso, categoria, fecha_venta),
CONSTRAINT FK_VENTAS FOREIGN KEY (cod_fabricante) REFERENCES FABRICANTES (cod_fabricante) ON DELETE CASCADE,
CONSTRAINT CH_VENTAS CHECK (unidades_vendidas >0),
CONSTRAINT FK_ventas3 FOREIGN KEY (articulo, cod_fabricante, peso, categoria) REFERENCES ARTICULOS (articulo, cod_fabricante, peso, categoria) ON DELETE CASCADE,
CONSTRAINT FK_VENTAS5 FOREIGN KEY (nif) REFERENCES TIENDAS (nif)
);


ALTER TABLE PEDIDOS MODIFY unidades_pedidas NUMBER(6);
ALTER TABLE VENTAS MODIFY unidades_vendidas NUMBER(6);
ALTER TABLE PEDIDOS ADD PVP NUMBER(10);
ALTER TABLE VENTAS ADD PVP NUMBER(10);
ALTER TABLE FABRICANTES DROP (pais);
ALTER TABLE VENTAS ADD CONSTRAINT CK_U CHECK (unidades_vendidas >=100);
ALTER TABLE VENTAS DROP CONSTRAINT CK_U;


DROP TABLE ARTICULOS CASCADE CONSTRAINT;
DROP TABLE FABRICANTES CASCADE CONSTRAINT;
DROP TABLE PEDIDOS CASCADE CONSTRAINT;
DROP TABLE VENTAS CASCADE CONSTRAINT;
DROP TABLE TIENDAS CASCADE CONSTRAINT;











